# Generated by Django 3.2 on 2021-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_rooms_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_amount',
            field=models.IntegerField(default=2),
        ),
    ]
